name: myApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - run: sudo rm -R /var/www/html
    - run: sudo cp -R /var/www/myApp/actions-runner/_work/walkover/walkover/build/. /var/www/html/
    - run: sudo service nginx restart
